src/Entity/Videogame.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideogameRepository")
 */
class Videogame
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $os;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $release_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Editor", inversedBy="videogames")
     */
    private $editor;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getOs(): ?string
    {
        return $this->os;
    }

    public function setOs(string $os): self
    {
        $this->os = $os;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getEditor(): ?editor
    {
        return $this->editor;
    }

    public function setEditor(?editor $editor): self
    {
        $this->editor = $editor;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Editor;
use App\Entity\Videogame;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        $user = $this->getUser();

        $videogames = $this->getDoctrine()
            ->getRepository(Videogame::class)
            ->findAll();

        $editors = $this->getDoctrine()
            ->getRepository(Editor::class)
            ->findAll();

        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'videogames' => $videogames,
            'editors' => $editors,
            'user' => $user,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    {% block title %}
        <title>
            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                Welcome {{ user.firstname }} {{ user.lastname }}!
            {% else %}
                Welcome!
            {% endif %}
        </title>
    {% endblock %}

    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }
    </style>

    <div class="example-wrapper">

        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            {% if user.firstname == "" or user.lastname == "" %}
                <h1>Welcome {{ user.email }} !</h1>
            {% else %}
                <h1>Welcome {{ user.firstname }} {{ user.lastname }} !</h1>
            {% endif %}
        {% else %}
            <h1>Welcome!</h1>
        {% endif %}
        <ul>
            {% for item in videogames %}
                <li>
                    <div class="col-12 ml-auto">
                        <div class="row">
                            {{ item.id }} - {{ item.title }} - {{ item.os }} - {{ item.releaseDate|date("Y/m/d") }}
                        </div>
                        <div class="row">
                            <p>{{ item.description }}</p>
                        </div>
                        <div class="row">
                            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                <a href="/videogame/{{ item.id }}">Details</a> &nbsp;
                            {% endif %}
                            {% if is_granted('ROLE_ADMIN') %}
                                <a href="/edit/videogame/{{ item.id }}">Modify</a> &nbsp;
                                <a href="/delete/videogame/{{ item.id }}">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <a href="/editors">Show Editors</a>
    </div>
    </body>
    </html>
{% endblock %}